test:
  image: python:3.8.6
  script:
    - pip3 install tox
    - tox

test-make-install-apt:
  image: $IMAGE
  stage: build
  only:
    - web
  before_script:
    - apt update -y && apt install -y make python3 python3-setuptools python3-pip
  script:
    - make && make install
  parallel:
    matrix:
      - IMAGE: ["ubuntu:bionic", "ubuntu:focal"]

test-make-install-dnf:
  image: $IMAGE
  stage: build
  only:
    - web
  before_script:
    - dnf update -y && dnf install -y make python3 python3-setuptools python3-pip
  script:
    - make && make install
  parallel:
    matrix:
      - IMAGE: ["fedora:32", "fedora:33", "centos:8"]

test-make-install-yum:
  image: $IMAGE
  stage: build
  only:
    - web
  before_script:
    - yum update -y && yum install -y make python3 python3-setuptools python3-pip
  script:
    - make && make install
  parallel:
    matrix:
      - IMAGE: ["centos:7"]

.test-dependencies:
  stage: test
  script:
    - python3 -m unittest blocksatcli/verify_deps_instal.py

test-deb-dependencies:
  image: $IMAGE
  extends: .test-dependencies
  only:
    - tags
    - web
  before_script:
    - apt update -y && apt install -y make python3 python3-setuptools python3-pip
    - make && make install
  parallel:
    matrix:
      - IMAGE: ["ubuntu:bionic", "ubuntu:focal"]

test-rpm-dependencies:
  image: $IMAGE
  extends: .test-dependencies
  only:
    - tags
    - web
  before_script:
    - dnf update -y && dnf install -y make python3 python3-setuptools python3-pip
    - make && make install
  parallel:
    matrix:
      - IMAGE: ["fedora:32", "fedora:33"]

pypi-upload:
  image: python
  stage: deploy
  only:
    refs:
      - tags
  script:
    - pip3 install twine
    - make pypi

docker-upload:
  image: docker
  stage: deploy
  only:
    refs:
      - tags
  before_script:
    - apk add make python3 py3-setuptools py3-pip
  script:
    - echo $DOCKERHUB_PW | docker login -u $DOCKERHUB_USER --password-stdin
    - make docker-push

pandoc:
  image:
    name: pandoc/latex
    entrypoint: [""]
  only:
    refs:
      - master
      - web
  before_script:
    - apk add python3
    - cd doc && ./pandoc_setup.sh
  script:
    - python3 pandoc.py
  artifacts:
    paths:
      - doc/blocksat_manual.pdf
